create table if not exists `%susers` (
    id bigint auto_increment unique not null,
    user_id bigint primary key,
    name varchar(128) not null,
    screen_name varchar(128) not null,
    location varchar(512) default null,
    description varchar(2048) default null,
    url text default null,
    followers_count bigint not null,
    friends_count bigint not null,
    listed_count bigint not null,
    favourites_count bigint not null,
    profile_background_color varchar(32) not null,
    profile_background_image_url text not null,
    profile_background_image_url_https text not null,
    profile_image_url text not null,
    profile_image_url_https text not null,
    profile_banner_url text not null,
    profile_link_color varchar(32) not null,
    profile_sidebar_border_color varchar(32) not null,
    profile_sidebar_fill_color varchar(32) not null,
    profile_text_color varchar(32) not null,
    created_at varchar(256) not null,
    update_at datetime not null
)engine=innodb  default charset=utf8mb4;
